version: 1.0.{build}
image: Visual Studio 2017
install: nuget restore .\src\HQ.Cadence.sln

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  
build:
  project: .\src\HQ.Cadence.sln
  verbosity: minimal

environment:
   TEST_PROJECT_NAME:
     HQ.Cadence.Tests
   XUNIT_CONSOLE_VERSION:
      2.4.0
   OPENCOVER_VERSION:
      4.6.519   
   COVERALLS_VERSION:
      1.0.0
   COVERALLS_REPO_TOKEN:  
      secure: ybaVTwokoDe5aIFj3RF2Aea5999hmNS7zaLNnSSy0tJkaC+3SJ3MpBbeTVZqF3q+
  
test_script:
- ps: >-
    nuget install xunit.runner.console -OutputDirectory packages -Version $env:XUNIT_CONSOLE_VERSION
    nuget install OpenCover -OutputDirectory packages -Version $env:OPENCOVER_VERSION
    dotnet tool install coveralls.net --version $env:COVERALLS_VERSION --tool-path tools
    .\packages\OpenCover.$env:OPENCOVER_VERSION\tools\OpenCover.Console.exe -register:user -target:dotnet.exe "-targetargs:"".\packages\xunit.runner.console.$env:XUNIT_CONSOLE_VERSION\tools\netcoreapp2.1\xunit.console.dll"" ""src\$env:TEST_PROJECT_NAME\bin\$env:CONFIGURATION\netcoreapp2.1\$env:TEST_PROJECT_NAME.dll"" -noshadow -appveyor" -filter:"+[*]*" -oldStyle -output:coverage.xml
    $coveralls = ".\tools\csmacnz.coveralls.exe" --opencover -i coverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID