version: 1.0.{build}
image: Visual Studio 2017
skip_tags: true
install: nuget restore .\src\HQ.Cadence.sln

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  
build:
  project: .\src\HQ.Cadence.sln
  verbosity: minimal

environment:
  COVERALLS_REPO_TOKEN:
    secure: T9CbXFG4JLSyZH/8mkjRSXpP4zzVSV4x3boRGkWvlsvCnVz94FVmQFSLnMETA7VH
  
# See: https://github.com/opencover/opencover/wiki/Usage#notes-on-spaces-in-arguments

test_script:
- ps: >-
    nuget install xunit.runner.console -OutputDirectory packages -Version 2.4.0

    dotnet tool install coveralls.net --version 1.0.0 --tool-path tools

    $coverageFilePath = Resolve-Path -path "TestResults\*\*.coverage"
 
    $coverageFilePath = $coverageFilePath.ToString()

    if(Test-Path .\coverage.xml) { rm .\coverage.xml }
        
    & "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe" analyze /output:coverage.xml "$coverageFilePath"

    $coveralls = "tools/csmacnz.Coveralls.exe"

    & $coveralls --dynamiccodecoverage -i .\coverage.xml --useRelativePaths