version: 1.0.{build}
image: Visual Studio 2017
skip_tags: true
install: nuget restore .\src\HQ.Cadence.sln

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  
build:
  project: .\src\HQ.Cadence.sln
  verbosity: minimal

environment:
  COVERALLS_REPO_TOKEN:
    secure: T9CbXFG4JLSyZH/8mkjRSXpP4zzVSV4x3boRGkWvlsvCnVz94FVmQFSLnMETA7VH
  
test_script:
- ps: >-
    nuget install xunit.runner.console -OutputDirectory packages -Version 2.4.0

    nuget install OpenCover -OutputDirectory packages -Version 4.6.519

    dotnet tool install coveralls.net --version 1.0.0 --tool-path tools

    # See: https://github.com/opencover/opencover/wiki/Usage#notes-on-spaces-in-arguments
    "packages/OpenCover.4.6.519/tools/OpenCover.Console.exe" -register:user -oldStyle -output:coverage.xml -target:dotnet.exe "-targetargs: -noshadow -appveyor .\packages\xunit.runner.console.2.4.0\tools\netcoreapp2.1\xunit.console.dll .\src\HQ.Cadence.Tests\bin\Release\netcoreapp2.1\HQ.Cadence.Tests.dll"

    $coveralls = "tools/csmacnz.Coveralls.exe"

    & $coveralls --opencover -i ./coverage.xml --useRelativePaths