version: 1.0.{build}
image: Visual Studio 2017
skip_tags: true
install: nuget restore .\src\HQ.Cadence.sln

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  
build:
  project: .\src\HQ.Cadence.sln
  verbosity: minimal

environment:
  COVERALLS_REPO_TOKEN:
    secure: T9CbXFG4JLSyZH/8mkjRSXpP4zzVSV4x3boRGkWvlsvCnVz94FVmQFSLnMETA7VH
  
# See: https://github.com/opencover/opencover/wiki/Usage#notes-on-spaces-in-arguments
# See: https://help.appveyor.com/discussions/problems/4394-problem-with-args-to-xunit-in-powershell

test_script:
- ps: >-
    dotnet tool install coveralls.net --version 1.0.0 --tool-path tools

    $assembly = ".\src\HQ.Cadence.Tests\bin\$env:CONFIGURATION\HQ.Cadence.Tests.dll"
    
    if(Test-Path .\coverage.xml) { rm .\coverage.xml }

    dotnet test ".\src\HQ.Cadence.Tests" -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=\coverage.xml

    $coveralls = "tools/csmacnz.Coveralls.exe"

    & $coveralls --opencover -i .\coverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID